version: '3.1'
services:

  web:
    build:
      context: .
      dockerfile: sbin/docker/node.dockerfile
    environment:
      - env=dev
    command: npm run prod
    volumes:
      - ./app:/vue/src/go-money
    ports:
      - 8081:8081

volumes:
  esdata1:
    driver: local